#!/usr/bin/env node
/**
 * hooks/update-readme.ts
 *
 * Auto-generates the "Skills in this repo" install table in README.md from
 * `skills/<name>/SKILL.md` frontmatter, grouped/ordered per skills.sh.json.
 *
 * Nobody should hand-write or guess install commands like
 * `npx -y skills add dzianisv/skills -s chrome-use -g` — this script derives
 * them from the skill directories so the table can never drift.
 *
 * Runs under BOTH Bun and Node 22+ (native TS type-stripping). Zero
 * dependencies: only node:fs / node:path / process. CommonJS on purpose
 * (require/__dirname) so module-type detection can't make Bun and Node
 * disagree about how to load this file.
 *
 * Usage:
 *   bun hooks/update-readme.ts
 *   node hooks/update-readme.ts
 *
 * Idempotent: running it twice in a row produces zero diff in README.md.
 */

const fs = require("node:fs");
const path = require("node:path");

// Single source of truth for the repo slug used in every install command.
// Deliberately NOT derived from `git remote` — keep this deterministic and
// offline so the hook never depends on network/git config at commit time.
const REPO_SLUG = "dzianisv/skills";

const ROOT = path.dirname(__dirname);
const SKILLS_DIR = path.join(ROOT, "skills");
const README_PATH = path.join(ROOT, "README.md");
const GROUPINGS_PATH = path.join(ROOT, "skills.sh.json");
const SKILLS_HEADING = "## Skills in this repo";

const START_MARKER =
  "<!-- SKILLS:START (auto-generated by hooks/update-readme.ts — do not edit) -->";
const END_MARKER = "<!-- SKILLS:END -->";

interface SkillInfo {
  name: string;
  summary: string;
}

interface Grouping {
  title: string;
  description?: string;
  skills: string[];
}

interface SkillsShConfig {
  notGrouped?: "top" | "bottom";
  groupings?: Grouping[];
}

// ---------------------------------------------------------------------------
// Minimal frontmatter parsing — no yaml dependency by design. Handles the
// four styles actually used across skills/*/SKILL.md: plain scalars,
// single-quoted, double-quoted, and folded block scalars (`key: >`).
// ---------------------------------------------------------------------------

function stripQuotes(raw: string): string {
  const v = raw.trim();
  if (v.length >= 2) {
    const first = v[0];
    const last = v[v.length - 1];
    if (first === '"' && last === '"') {
      return v.slice(1, -1).replace(/\\"/g, '"').replace(/\\\\/g, "\\");
    }
    if (first === "'" && last === "'") {
      return v.slice(1, -1).replace(/''/g, "'");
    }
  }
  return v;
}

function parseFrontmatter(content: string): Record<string, string> {
  const lines = content.split("\n");
  if (lines[0]?.trim() !== "---") return {};

  let end = -1;
  for (let i = 1; i < lines.length; i++) {
    if (lines[i].trim() === "---") {
      end = i;
      break;
    }
  }
  if (end === -1) return {};

  const fmLines = lines.slice(1, end);
  const result: Record<string, string> = {};

  for (let i = 0; i < fmLines.length; i++) {
    const line = fmLines[i];
    // Only top-level "key: value" lines (no leading whitespace) start a new
    // field. Indented lines (list items, nested maps, already-consumed block
    // scalar bodies) are handled inline below or skipped here.
    const m = /^([A-Za-z_][\w-]*):[ \t]?(.*)$/.exec(line);
    if (!m) continue;

    const key = m[1];
    let value = m[2];
    const trimmedValue = value.trim();
    const blockMatch = /^([>|])[+-]?\s*$/.exec(trimmedValue);

    if (blockMatch) {
      // Folded (">") or literal ("|") block scalar: consume subsequent
      // indented (or blank) lines until dedent / next key / end of frontmatter.
      const folded = blockMatch[1] === ">";
      const collected: string[] = [];
      let j = i + 1;
      while (j < fmLines.length && (fmLines[j].trim() === "" || /^\s+/.test(fmLines[j]))) {
        collected.push(fmLines[j].trim());
        j++;
      }
      i = j - 1;
      value = folded ? collected.filter((l) => l.length > 0).join(" ") : collected.join("\n");
    } else {
      value = stripQuotes(value);
    }

    result[key] = value;
  }

  return result;
}

// First sentence: up to the first ". " (or ".") at end of string. Falls back
// to the whole (whitespace-collapsed) description when no sentence boundary
// is found, so short one-sentence descriptions still work.
function firstSentence(text: string): string {
  const cleaned = text.replace(/\s+/g, " ").trim();
  const m = /^(.*?\.)(?:\s|$)/.exec(cleaned);
  return (m ? m[1] : cleaned).trim();
}

function escapeCell(text: string): string {
  return text.replace(/\s+/g, " ").replace(/\|/g, "\\|").trim();
}

// ---------------------------------------------------------------------------
// Collect skills
// ---------------------------------------------------------------------------

function loadSkills(): Map<string, SkillInfo> {
  const skills = new Map<string, SkillInfo>();
  const dirs = fs
    .readdirSync(SKILLS_DIR, { withFileTypes: true })
    .filter((d: any) => d.isDirectory())
    .map((d: any) => d.name)
    .sort();

  for (const name of dirs) {
    const skillMdPath = path.join(SKILLS_DIR, name, "SKILL.md");
    if (!fs.existsSync(skillMdPath)) {
      console.warn(`update-readme: skipping "${name}" — no SKILL.md found`);
      continue;
    }
    const content = fs.readFileSync(skillMdPath, "utf8");
    const fm = parseFrontmatter(content);
    const fmName = fm.name || name;
    const description = fm.description || "";
    const summary = fm.summary ? fm.summary.replace(/\s+/g, " ").trim() : firstSentence(description);

    skills.set(name, { name: fmName, summary });
  }

  return skills;
}

function loadGroupings(): SkillsShConfig {
  const raw = fs.readFileSync(GROUPINGS_PATH, "utf8");
  return JSON.parse(raw) as SkillsShConfig;
}

// ---------------------------------------------------------------------------
// Render
// ---------------------------------------------------------------------------

function installCommand(dirName: string): string {
  return `npx -y skills add ${REPO_SLUG} -s ${dirName} -g`;
}

function renderTable(dirNames: string[], skills: Map<string, SkillInfo>): string[] {
  const lines: string[] = [];
  lines.push("| Skill | What it does | Install |");
  lines.push("|-------|--------------|---------|");
  for (const dirName of dirNames) {
    const info = skills.get(dirName);
    if (!info) continue;
    const cmd = installCommand(dirName);
    lines.push(`| [\`${dirName}\`](skills/${dirName}) | ${escapeCell(info.summary)} | \`${cmd}\` |`);
  }
  return lines;
}

function buildGeneratedBlock(skills: Map<string, SkillInfo>, config: SkillsShConfig): string[] {
  const groupings = config.groupings || [];
  const consumed = new Set<string>();
  const blockLines: string[] = [];

  for (const grouping of groupings) {
    const dirNames: string[] = [];
    for (const skillName of grouping.skills || []) {
      if (!skills.has(skillName)) {
        console.warn(
          `update-readme: skills.sh.json grouping "${grouping.title}" references unknown skill "${skillName}" — skipping`,
        );
        continue;
      }
      if (consumed.has(skillName)) {
        console.warn(
          `update-readme: skill "${skillName}" listed in multiple skills.sh.json groupings — using first occurrence`,
        );
        continue;
      }
      consumed.add(skillName);
      dirNames.push(skillName);
    }
    if (dirNames.length === 0) continue;

    blockLines.push(`### ${grouping.title}`);
    blockLines.push("");
    if (grouping.description) {
      blockLines.push(grouping.description);
      blockLines.push("");
    }
    blockLines.push(...renderTable(dirNames, skills));
    blockLines.push("");
  }

  const ungrouped = [...skills.keys()].filter((n) => !consumed.has(n)).sort();
  if (ungrouped.length > 0) {
    const otherBlock: string[] = [];
    otherBlock.push("### Other");
    otherBlock.push("");
    otherBlock.push(...renderTable(ungrouped, skills));
    otherBlock.push("");

    if (config.notGrouped === "top") {
      blockLines.unshift(...otherBlock);
    } else {
      blockLines.push(...otherBlock);
    }
  }

  // Trim a single trailing blank line so marker placement stays tidy.
  while (blockLines.length > 0 && blockLines[blockLines.length - 1] === "") {
    blockLines.pop();
  }

  return blockLines;
}

// ---------------------------------------------------------------------------
// README injection
// ---------------------------------------------------------------------------

function injectIntoReadme(readme: string, generatedBlock: string[]): string {
  const hadTrailingNewline = readme.endsWith("\n");
  const lines = readme.split("\n");

  const markerBlock = [START_MARKER, "", ...generatedBlock, "", END_MARKER];

  const startIdx = lines.findIndex((l) => l.trim() === START_MARKER);
  const endIdx = lines.findIndex((l) => l.trim() === END_MARKER);

  let newLines: string[];

  if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
    // Subsequent run: replace only what's between (and including) markers.
    newLines = [...lines.slice(0, startIdx), ...markerBlock, ...lines.slice(endIdx + 1)];
  } else {
    // First run: markers absent — replace the hand-written table that
    // follows "## Skills in this repo", preserving the heading and any
    // intro paragraph before it, and everything after the table.
    const headingIdx = lines.findIndex((l) => l.trim() === SKILLS_HEADING);
    if (headingIdx === -1) {
      throw new Error(
        `update-readme: could not find "${SKILLS_HEADING}" heading in README.md — add it manually before running this script`,
      );
    }

    let tableStart = -1;
    for (let i = headingIdx + 1; i < lines.length; i++) {
      if (lines[i].trimStart().startsWith("|")) {
        tableStart = i;
        break;
      }
      // Stop looking once we hit the next heading with no table found.
      if (/^#{1,6}\s/.test(lines[i])) break;
    }

    if (tableStart === -1) {
      // No existing table found — insert the generated block right after
      // the heading (and its intro paragraph, up to the next blank line
      // followed by content, or next heading).
      let insertAt = headingIdx + 1;
      while (insertAt < lines.length && !/^#{1,6}\s/.test(lines[insertAt])) insertAt++;
      newLines = [...lines.slice(0, insertAt), ...markerBlock, "", ...lines.slice(insertAt)];
    } else {
      let tableEnd = tableStart;
      while (tableEnd < lines.length && lines[tableEnd].trim().startsWith("|")) tableEnd++;
      newLines = [...lines.slice(0, tableStart), ...markerBlock, ...lines.slice(tableEnd)];
    }
  }

  let out = newLines.join("\n");
  if (hadTrailingNewline && !out.endsWith("\n")) out += "\n";
  return out;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  const skills = loadSkills();
  const config = loadGroupings();
  const generatedBlock = buildGeneratedBlock(skills, config);

  const originalReadme = fs.readFileSync(README_PATH, "utf8");
  const updatedReadme = injectIntoReadme(originalReadme, generatedBlock);

  if (updatedReadme === originalReadme) {
    console.log(`update-readme: README.md already up to date (${skills.size} skills, no changes)`);
    return;
  }

  fs.writeFileSync(README_PATH, updatedReadme);
  console.log(`update-readme: README.md updated — ${skills.size} skills across groups from skills.sh.json`);
}

main();
